value = input('Type something: ')
print(f'The primitive type of this value is {type(value)}')
print(f'Only have spaces? {value.isspace()}')
print(f'Is it a number? {value.isnumeric()}')
print(f'Is it an alphabetic? {value.isalpha()}')
print(f'Is it an alpha-numeric? {value.isalnum()}')
print(f'Is it uppercase? {value.isupper()}')
print(f'Is it lowercase? {value.islower()}')
print(f'Is it title-cased? {value.istitle()}')
